### PR TITLE
Context scope fix

### PR DESCRIPTION
**Pull request by samueljoos**
This is a fix for #11. The context was missing when using {{ var }} inside a {{#each in}} loop.
I think it is better idea to create a context variable in every block scope instead of using this.data.

There was also a problem with variables and whitespace. I have added a small fix for that too

### CODE REVIEW

**Comment by timbrandin** [comment]
The code looks good, but the branch has conflicts that need to be resolved, could you update your PR?

**Comment by samueljoos** [comment]
The merge conflicts are resolved now.

**Comment by timbrandin** [comment]
LGTM

**Comment by timbrandin** [comment]
I hope I can do a new release tonight with your changes, probs only a minor, I have tons of other stuff I need to get in for Meteor 1.2 also. :)

**Pull request merged**
